name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Install dependencies
      run: npm ci || npm install
    
    - name: Initialize database
      run: node init-db.js
    
    - name: Start server in background
      run: |
        npm start &
        sleep 5
    
    - name: Test server
      run: |
        curl http://localhost:3000/api/test || exit 1
    
    - name: Stop server
      run: pkill node || true 